# Generated by ChatGPT3
#
#
#.\Show-WindowsPackage.ps1 -ComponentName "Microsoft-Windows-PrintService-Features-Package"

#This will display information about the package that corresponds to the specified component, such as the package name, family name, and version.

Note: The script uses the Windows Management Instrumentation (WMI) to query information about the packages and components installed on the system. The script assumes that you have administrative privileges on the computer and are running PowerShell on a Windows operating system.
param ($ComponentName)

$WmiNamespace = "root\cimv2\mdm\dmmap"
$WmiQuery = "SELECT * FROM MDM_DCM_Package WHERE Component = '$ComponentName'"

Get-WmiObject -Namespace $WmiNamespace -Query $WmiQuery |
    Select-Object Component, PackageName, PackageFamilyName, PackageVersion
