# Generated by ChatGPT3
#
# This cmdlet installs the Server-Gui-Mgmt-Infra feature, which includes the GUI and management infrastructure components of the Windows Server operating system. The -IncludeAllSubFeature and -IncludeManagementTools parameters include all subfeatures and management tools in the installation. The -Restart parameter specifies that the system should be restarted after the upgrade is completed.
#
# Modified it, so you don't need to specify the wim file
#
# Mount the ISO file
Mount-DiskImage -ImagePath "D:\Sources\install.iso"

# Get the mounted volume
$volume = Get-Volume | Where-Object {$_.DriveType -eq 'CD'}

# Specify the source media for the upgrade
$source = $volume.Path

# Specify the source media for the upgrade
# $source = "D:\Sources\install.wim"

# Install the Windows feature
Install-WindowsFeature -Name "Server-Gui-Mgmt-Infra" -Source $source -IncludeAllSubFeature -IncludeManagementTools -Restart

# Unmount the ISO file
# Dismount-DiskImage -ImagePath "D:\Sources\install.iso"
