# Generated by ChatGPT3
#
# This script uses the Active Directory module in PowerShell to connect to the AD domain and import the necessary cmdlets. It then uses the Get-ADObject cmdlet to retrieve the distinguished name (DN) of the computer object that was deleted and is still in the recycle bin. The Select-Object cmdlet is used to expand the DistinguishedName property of the object and store it in the $computerDN variable.
#
# The Restore-ADObject cmdlet is used to restore the computer object.
#
# Next, the script uses the Get-ADObject cmdlet to retrieve the DN of the BitLocker recovery key information for the computer object, based on the object's msFVE-RecoveryGuid property. The Where-Object cmdlet is used to filter the results based on the objectGUID property of the computer object, which is retrieved using the Get-ADObject cmdlet with the -IncludeDeletedObjects parameter. The Select-Object cmdlet is used to expand the DistinguishedName property of the object and store it in the $keyDN variable.
#
# Finally, the Restore-ADObject cmdlet is used to restore the BitLocker recovery key information.


# Import the Active Directory module
Import-Module ActiveDirectory

# Connect to the AD domain
$cred = Get-Credential
$session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri "http://server01.contoso.com/PowerShell/" -Credential $cred
Import-PSSession $session

# Get the distinguished name (DN) of the computer object that was deleted and is still in the recycle bin
$computerDN = Get-ADObject -Filter {isDeleted -eq $true -and objectClass -eq "ComputerName"} -IncludeDeletedObjects | Select-Object -ExpandProperty DistinguishedName

# Restore the computer object
Restore-ADObject -Identity $computerDN

# Get the DN of the BitLocker recovery key information for the computer object
$keyDN = Get-ADObject -Filter {objectClass -eq "msFVE-RecoveryInformation" -and msFVE-RecoveryPassword -ne $null} -IncludeDeletedObjects | Where-Object {$_.msFVE-RecoveryGuid -eq (Get-ADObject -Identity $computerDN -Properties objectGUID -IncludeDeletedObjects).objectGUID} | Select-Object -ExpandProperty DistinguishedName

# Restore the BitLocker recovery key information
Restore-ADObject -Identity $keyDN
